### PR TITLE
Added dvc and touched up readme.md

### PR DESCRIPTION
**Pull request by LarryBattle**
This PR is a possible solution to add the DVC tool to the readme. ( issue https://github.com/josephmisiti/awesome-machine-learning/issues/551 )

Basically, I wrapped everything in a parent group called "Frameworks and Libraries". Then added a "Tools" section next to it. From there I placed the [DVC]() tool inside the `tool-misc` group.

## Screenshot
dvc_in_readme md

## Related issue
https://github.com/josephmisiti/awesome-machine-learning/issues/551

## Demo

https://github.com/LarryBattle/awesome-machine-learning/blob/feature/add_dvc_to_readme.md/README.md

### CODE REVIEW

**Comment by shcheklein** [comment]
@LarryBattle this looks great! I would change a description a little bit, at least to make all lower case. Consider something like this:

Data Science Version Control is an open-source version control system for machine learning projects with pipelines support. It makes ML projects reproducible and shareable.

Thanks!

**Comment by shcheklein** [comment]
Btw, since the list of tools is small (only one item now), may be we can keep it one level - just Tools? It will be enough for a while, then we can introduce some structure. What do you think?

**Comment by josephmisiti** [comment]
should i merge this in ?

**Comment by shcheklein** [comment]
@josephmisiti let's merge, and I will submit an improvement if @LarryBattle does not mind

**Comment by LarryBattle** [comment]
Updated the description. Merge whenever you like.

**Comment by josephmisiti** [comment]
thanks

**Pull request merged**
