### PR TITLE
Update redirects in Readme

### PR DESCRIPTION
**Pull request by ReadmeCritic**
Created with https://github.com/dkhamsing/frankenstein

### CODE REVIEW

**Comment by josephmisiti** [comment]
sorry - a bit confused - what is this doing exactly ?

**Comment by ReadmeCritic** [comment]
It's replacing links that are http redirected
i.e.
https://github.com/tqchen/xgboost was changed to https://github.com/dmlc/xgboost

**Comment by josephmisiti** [comment]
thanks!

**Comment by ReadmeCritic** [comment]
:tada:

**Pull request merged**
