### PR TITLE
Spellings Corrected

### PR DESCRIPTION
**Pull request by snehaldalvi**
I have corrected all the typos and made some corrections in sentences in the readme file.

### CODE REVIEW

**Comment by spekulatius** [comment]
Spam...

**Comment by josephmisiti** [comment]
@spekulatius is it spam ? It just looks like a bunch of corrections to me?

**Comment by snehaldalvi** [comment]
It's not spam. I just made a few corrections I came across just typos

**Comment by r-hassan-zz** [comment]
unsubscribe

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by spekulatius** [comment]
> @spekulatius is it spam ? It just looks like a bunch of corrections to me?

There are typos fixed in there, but also new typos and issues. E.g.: https://github.com/josephmisiti/awesome-machine-learning/pull/734/files#diff-04c6e90faac2675aa89e2176d2eec7d8L205

**Pull request merged**
