### PR TITLE
New:changes

### PR DESCRIPTION
**Pull request by austin-tp**
This is contrribution

### CODE REVIEW

**Comment by josephmisiti** [comment]
no it is not.

**Comment by spekulatius** [comment]
context: https://blog.domenic.me/hacktoberfest/

Want to mark is as spam @josephmisiti ?

**Comment by josephmisiti** [comment]
@spekulatius done

**Comment by spekulatius** [comment]
Awesome, thank you. It's important to put Digital Ocean to this growing issue for open source.

**Comment by josephmisiti** [comment]
@spekulatius yes it is very annoying.

**Comment by spekulatius** [comment]
Indeed, and really pointless on top. I'll help with the clean up

**Pull request closed without merging**
