### PR TITLE
I have added a Data Science Interview Questions and answers PDF... Please merge it into your Repo

### PR DESCRIPTION
**Pull request by Nitish-McQueen**

### CODE REVIEW

**Comment by spekulatius** [comment]
Spam...

**Comment by Nitish-McQueen** [comment]
> Spam...

Bro first of all open the document read it then tell me is it a spam or not.
Otherwise, I think you have studied wrong about Spam.

**Comment by spekulatius** [comment]
Randomly adding a document without any context looks a lot like it...

**Comment by Nitish-McQueen** [comment]
No No ... Not randomly. Let me explain
I have seen your repo "Awesome Machine Learning ". In the README section, i have seen you have posted some links for Books, Courses, Blogs, Newsletters.
That's why I think this Data Science Interview question answer PDF will helpful for other peoples.

Please let me know what you think about my response.

**Comment by Shanky-21** [comment]
@Nitish-McQueen  Saw you adding the same pdf file in few more machine learning repositories. LOL @spekulatius

**Comment by Nitish-McQueen** [comment]
Yes, Shanky-21. It is for everyone's help not for selected.

**Comment by josephmisiti** [comment]
I saw this and am now closing this PR: https://twitter.com/jakevdp/status/1311733240302989313

**Pull request closed without merging**
