### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jeffreyjackson**
Spellchecking :beers: :grimacing:

### CODE REVIEW

**Comment by josephmisiti** [comment]
thanks!

**Comment by jeffreyjackson** [comment]
any interest in the issue I opened for AwesomeOpenSource?

**Comment by josephmisiti** [comment]
ill wait to see what everyone else does :)

**Comment by jeffreyjackson** [comment]
sure thing :) cc @dkhamsing

**Pull request merged**
