### PR TITLE
Added a link to DataVisualization Repository

### PR DESCRIPTION
**Pull request by Shanky-21**
As always Hands on Experience is always more helpful to learn any concept.

This Repository Contains many Notebooks for DataVisualization techniques using Python Language. 

1. Introduction-to-Matplotlib-and-Line-Plots
2. Pie-Charts-Box-Plots-Scatter-Plots-and-Bubble-Plots
3. Waffle-Charts-Word-Clouds-and-Regression-Plots
4. Area-Plots-Histograms-and-Bar-Charts
5. working with Artist layer of matplotlib
6. Proj-Loan-answer - This one is of mine. 
I have collected most of these notebooks from coursera courses. I have also made one of them and working with artist layer is downloaded from google. 

Kindly merge this PR. I really have done some work for getting this PR accepted. Followed all your rules. It will be very helpful to everyone want to learn Datavisualization.

I'll be adding one more PR on machine learning Basic Algorithms Notebooks. Like Recommender system, Clustering, Classification, Regression in about two hours

### CODE REVIEW

**Comment by Shanky-21** [comment]
Hello, sir. I've added Machine learning Repository too. Please Review it. and merge it

**Comment by Shanky-21** [comment]
Sir can you please add hacktoberfest accepted label to this PR. I will be very thank full to you. 
I will be contributing regularly to this repo

**Comment by josephmisiti** [comment]
@Shanky-21 why ?

**Comment by Shanky-21** [comment]
I recieved a mail by hactoberfest that they have updated their rules and now. To get my pr accepted for hactoberfest. PR should be merged and labelled as hactoberfest accepted label. So if you label my PR it will get accepted for my hacktoberfest challenge completion.

**Comment by Shanky-21** [comment]
I did some introspection. Thankyou for merging my PR, honestly this is my first PR merged in a big repository like yours. Whether you label it or not I am happy. At least I have learned how to contribute and a wide smile on my face knowing my PR got merged. Thankyou.

**Comment by josephmisiti** [comment]
i added the tag. let me know if there are any other issues.

**Comment by Shanky-21** [comment]
IMG_20201006_030614

The label needed is --> hacktoberfest-accepted

**Comment by josephmisiti** [comment]
done.

**Pull request merged**
